language: python
matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: pypy3
install:
  - pip install --upgrade pip
  - pip install pytest coverage
  - pip install -e .
script:
  - coverage run -m pytest --verbose
  - coverage report -i -m